### PR TITLE
add .devcontainer config

### LINKED ISSUE #26: Add devcontainer configuration to the repository

### PR DESCRIPTION
**Pull request by Zaubeerer**

### CODE REVIEW

**Comment by Zaubeerer** [comment]
Role switch :) 

Feel free to test this dev container locally by `>devcontainers: rebuild and reopen in container`.

Locally, this worked for me (although there is currently an error message related to the last command for the entrypoint I guess.

I tested the devcontainer config by creating a codespace for this feature branch.

Let me know if you have any questions!

**Comment by Shuaib-8** [comment]
Hi Robin,

I think it's all good - see my loom.

https://www.loom.com/share/74877d6a4a6f459cb105ef8ff514a2fd

The only thing I needed clarifying was that this dev container allows us to run like our own computer basically (in this case streamlit so `streamlit run`) so just launching the app etc as opposed to doing `docker build` and then starting up again and again?

**Comment by Zaubeerer** [comment]
Yes, if I understand your question correctly :)

devcontainers are actually docker container (you can check in your docker desktop application). 

Hence, you are already in the docker container and thus you can simply run the streamlit run command :)

**Comment by Zaubeerer** [comment]
So I guess we can merge this change?

Or do you have any open questions?

**Comment by Shuaib-8** [comment]
Last question I have:

- illustrating **dev container** repo on remote - is this ok, or should it not be tracked online and then defined within `.gitignore`?

**Comment by Shuaib-8** [comment]
Yep besides the question, thanks for clarifying. 
It is another excellent tool and another reason why VSCode shines 🙌🏼 !

**Comment by Zaubeerer** [comment]
> illustrating dev container repo on remote - is this ok, or should it not be tracked online and then defined within .gitignore?

Hmm, I did not understand your question 🤔

**Comment by Shuaib-8** [comment]
> > illustrating dev container repo on remote - is this ok, or should it not be tracked online and then defined within .gitignore?
> 
> Hmm, I did not understand your question 🤔

Is it ok to have `devcontainer` content committed online or should I hide them away only for personal use (AKA stuff it in .gitignore)?

**Pull request merged**
